# Generated by Django 2.2.5 on 2019-09-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20190318_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
